"use client";
import React from "react";
import { Table, TableHeader, TableColumn, TableBody, TableRow, TableCell, Link } from "@nextui-org/react";

function TableJadwal() {
  const Jadwal = [
    {
      IdHari: 0,
      IdJam: 3,
      IdKuliah: 66395,
      Keterangan: null,
      Hari: "SENIN",
      Ruang: "05.02.03",
      Waktu: "10:40-12:20",
      ZoomURL: "https://zoom.us/j/96731677231",
      IsZoomURL: 1,
      Kode: "ST044",
      MataKuliah: "METODE NUMERIK",
      JenisKuliah: "Teori",
      Kelas: "21S1IF07-MetodeN(ST044)",
      Nik: "190302246",
      NamaDosen: "Rumini, M.Kom",
      EmailDosen: "rumini@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 5,
      IdKuliah: 66615,
      Keterangan: null,
      Hari: "SENIN",
      Ruang: "VR.01.02",
      Waktu: "15:30-17:10",
      ZoomURL: "https://zoom.us/j/96902430672",
      IsZoomURL: 1,
      Kode: "ST120",
      MataKuliah: "BAHASA INDONESIA",
      JenisKuliah: "Teori",
      Kelas: "21S1IF07-BahasaI(ST120)",
      Nik: "190302599",
      NamaDosen: "Junaidi, S.Ag., M.Hum, Dr.",
      EmailDosen: "junaidi.i@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 3,
      IdKuliah: 66627,
      Keterangan: null,
      Hari: "SELASA",
      Ruang: "07.01.02",
      Waktu: "10:40-12:20",
      ZoomURL: "https://zoom.us/j/92912228003",
      IsZoomURL: 1,
      Kode: "ST168",
      MataKuliah: "BIG DATA DAN DATA MINING",
      JenisKuliah: "Teori",
      Kelas: "21S1IF-BigData5(ST168)",
      Nik: "190302112",
      NamaDosen: "Kusnawi, S.Kom, M. Eng.",
      EmailDosen: "khusnawi@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 5,
      IdKuliah: 66662,
      Keterangan: null,
      Hari: "SELASA",
      Ruang: "05.04.08",
      Waktu: "15:30-17:10",
      ZoomURL: "https://zoom.us/j/95664096215",
      IsZoomURL: 1,
      Kode: "ST154",
      MataKuliah: "INTERNET OF THINGS",
      JenisKuliah: "Teori",
      Kelas: "21S1IF07-Interne(ST154)",
      Nik: "190302707",
      NamaDosen: "Bambang Pilu Hartato, S.Kom., M.Eng",
      EmailDosen: "bambang.pilu@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 1,
      IdKuliah: 67300,
      Keterangan: null,
      Hari: "RABU",
      Ruang: "05.03.06",
      Waktu: "07:00-08:40",
      ZoomURL: "https://zoom.us/j/95866066953",
      IsZoomURL: 1,
      Kode: "ST150",
      MataKuliah: "KEPEMIMPINAN",
      JenisKuliah: "Teori",
      Kelas: "21S1IF07-Kepemim(ST150)",
      Nik: "190302581",
      NamaDosen: "Narwanto Nurcahyo, SH, MM",
      EmailDosen: "narwanto.n@amikom.ac.id ",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 3,
      IdKuliah: 66655,
      Keterangan: null,
      Hari: "RABU",
      Ruang: "05.03.04",
      Waktu: "10:40-12:20",
      ZoomURL: "https://zoom.us/j/95397091178",
      IsZoomURL: 1,
      Kode: "ST163",
      MataKuliah: "INOVASI PEMBAYARAN DIGITAL",
      JenisKuliah: "Teori",
      Kelas: "21S1IF-Inovasi5(ST163)",
      Nik: "190302706",
      NamaDosen: "Enda Putri Atika, M.Kom",
      EmailDosen: "endaputri@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 5,
      IdKuliah: 66672,
      Keterangan: null,
      Hari: "RABU",
      Ruang: "05.03.01",
      Waktu: "15:30-17:10",
      ZoomURL: "https://zoom.us/j/91280617326",
      IsZoomURL: 1,
      Kode: "ST108",
      MataKuliah: "E-COMMERCE",
      JenisKuliah: "Teori",
      Kelas: "21S1IF07-ECommer(ST108)",
      Nik: "190302492",
      NamaDosen: "Mujiyanto, M.Kom",
      EmailDosen: "mujiyanto@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 2,
      IdKuliah: 66411,
      Keterangan: null,
      Hari: "KAMIS",
      Ruang: "07.01.01",
      Waktu: "08:50-10:30",
      ZoomURL: "https://zoom.us/j/98777189740",
      IsZoomURL: 1,
      Kode: "ST170",
      MataKuliah: "REKAYASA PERANGKAT LUNAK",
      JenisKuliah: "Teori",
      Kelas: "21S1IF-Rekayas6(ST170)",
      Nik: "190302226",
      NamaDosen: "Emigawaty, M.Kom",
      EmailDosen: "emigawaty@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 3,
      IdKuliah: 66628,
      Keterangan: "",
      Hari: "KAMIS",
      Ruang: "L 2.4.3",
      Waktu: "10:40-12:20",
      ZoomURL: "https://zoom.us/j/97967960975",
      IsZoomURL: 1,
      Kode: "ST168",
      MataKuliah: "BIG DATA DAN DATA MINING",
      JenisKuliah: "Praktikum",
      Kelas: "21S1IF-BigData5(ST168)",
      Nik: "190302112",
      NamaDosen: "Kusnawi, S.Kom, M. Eng.",
      EmailDosen: "khusnawi@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 4,
      IdKuliah: 66411,
      Keterangan: null,
      Hari: "KAMIS",
      Ruang: "07.01.01",
      Waktu: "13:20-15:00",
      ZoomURL: "https://zoom.us/j/98777189740",
      IsZoomURL: 1,
      Kode: "ST170",
      MataKuliah: "REKAYASA PERANGKAT LUNAK",
      JenisKuliah: "Teori",
      Kelas: "21S1IF-Rekayas6(ST170)",
      Nik: "190302226",
      NamaDosen: "Emigawaty, M.Kom",
      EmailDosen: "emigawaty@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 4,
      IdKuliah: 66396,
      Keterangan: "",
      Hari: "JUMAT",
      Ruang: "VL.01",
      Waktu: "13:20-15:00",
      ZoomURL: "https://zoom.us/j/95298934093",
      IsZoomURL: 1,
      Kode: "ST044",
      MataKuliah: "METODE NUMERIK",
      JenisKuliah: "Praktikum",
      Kelas: "21S1IF07-MetodeN(ST044)",
      Nik: "190302246",
      NamaDosen: "Rumini, M.Kom",
      EmailDosen: "rumini@amikom.ac.id",
      Jenjang: "S1",
    },
    {
      IdHari: 0,
      IdJam: 5,
      IdKuliah: 66419,
      Keterangan: "",
      Hari: "JUMAT",
      Ruang: "L 7.3.1",
      Waktu: "15:30-17:10",
      ZoomURL: "https://zoom.us/j/98982565524",
      IsZoomURL: 1,
      Kode: "ST153",
      MataKuliah: "BIG DATA & PREDICTIVE ANALYTICS LANJUT",
      JenisKuliah: "Praktikum",
      Kelas: "21S1IF07-BigData(ST153)",
      Nik: "190302705",
      NamaDosen: "Ajie Kusuma Wardhana, S.Kom., M.Eng",
      EmailDosen: "ajiekusuma@amikom.ac.id",
      Jenjang: "S1",
    },
  ];
  return (
    <div className="lg:px-10">
      <Table aria-label="Example table with dynamic content">
        <TableHeader>
          <TableColumn align="center">Hari</TableColumn>
          <TableColumn align="center">Waktu</TableColumn>
          <TableColumn align="center">Mata Kuliah</TableColumn>
          <TableColumn align="center">Kelas</TableColumn>
          <TableColumn align="center">Dosen</TableColumn>
          <TableColumn align="center">Ruang</TableColumn>
          <TableColumn align="center">Zoom</TableColumn>
        </TableHeader>
        <TableBody>
          {Jadwal.map((item) => (
            <TableRow key={item.IdKuliah}>
              <TableCell align="center">{item.Hari}</TableCell>
              <TableCell align="center">{item.Waktu}</TableCell>
              <TableCell align="center">{item.MataKuliah}</TableCell>
              <TableCell align="center">{item.Kelas}</TableCell>
              <TableCell align="center">{item.NamaDosen}</TableCell>
              <TableCell align="center">{item.Ruang}</TableCell>
              <TableCell align="center">
                <Link href={item.ZoomURL} target="_blank">Zoom</Link>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

export default TableJadwal;
